### PR TITLE
Option to prevent or stop low speed GPU fan flickering

### PR DESCRIPTION
**Pull request by tzh1043**
The fans of some GPUs start to rapidly turn on and off at low speeds [1],
sometimes called "fan flickering".

One workaround is to only gradually lower the fan speed when in the
range where this happens. Raising also happens slower, but this
does not prevent this issue as reliably. Therefore flickering is also
detected: then the speed is increased back out of the flicker zone before
lowering it again.

The range is defined as a speed% where the flickering starts, and below that
a minimum speed% down to where the fan can be carefully lowered: [min, start].
Going lower than `min` means flickering happens all the time, but above `start`
arbitrary jumps cause no problems.

The zone range can be set via a config file option `fanflicker = [min, start]`
or on the command line via `-r, --fanflicker`. These are specified in %.
The command line overrides the config file, `-r 0` turn this feature off.

This also means the fan will always spin with at least `min` speed and will
not turn off completely. Also since up to `start` the fans might take some time
to reach the given speed, the corresponding temperature must not exceed 75°C.

E.g. `fanflicker = [11, 38]` means when going below 11% the fan always
flickers but behaves normally at 38%. So between these values speed changes
are applied gradually, currently -1 or +2 every 2 seconds.

1: https://forums.guru3d.com/threads/rtx-series-low-fan-speed-revving-noise-and-turn-on-off-problem.423708/
   http://forum.gigabyte.us/thread/5546/rtx2070-windforce-fan-flickering-issue
   https://www.techpowerup.com/forums/threads/gpu-fan-spins-up-and-down-when-idle.219471/

### CODE REVIEW

**Comment by tzh1043** [comment]
RFC. Also never tested it with configs which DO turn off GPU fans at low temps because that would not mean going from [OFF] to 25% or so but directly to 38% or whatever the flicker cutoff, and _then_ lowering it again.

**Comment by foucault** [comment]
Firstly many thanks for your contribution!! It would've been impossible for me to detect this issue. It is very frustrating to see the amount of assumptions OEM firmware make as to what people should except (or not) as far as the thermal behaviour of the card is concerned. This is really an issue that should've been fixed in firmware instead of relying on workarounds but, oh well!

That being said I have the following minor issues with your commit
1. There should really be a command line option for this (similar to how the `-l` or `--limits` option works). This also allows to support legacy configs as well (which are essentially just a bunch of points).
2. I see duplicate commints between this PR and PR #14. I will merge PR #14 so please rebase this PR along with any changes from point 1 on the new commit.

I apologise if I made any erroneous assumptions and please correct me if that's the case :-)

**Comment by tzh1043** [comment]
Indeed, the other PR was stuff which was good to go.

I added a `-r, --fanflicker` option which I initially stopped working on because I though the config file was the preferred way now. The intermediary arg parsing and config file stuff was in the other PR.

This new patch now also keeps the fan spinning when the curve stops.

And indeed, I was waiting for a GPU firmware fix, but that never came, so here I am! And according to some posts this issue seems to be present in newer and older generations of cards...

This fix/hack should probably be tested by others like the posters in the mentioned forums, but I can't create windows binaries. Could you prepare a beta or pre-release?

**Comment by foucault** [comment]
Great, it's much better now; thanks! I'll do away with the old config format eventually but in the meantime let's keep things simple. What is not clear to me now is which one of this has precedence: the *limits* or the *fan flicker threshold*? For instance if you put `[11, 38]` as flicker parameters the fan will always be at 11% even when "off". What happens if the limits are set higher (like `[20, 80]` which is the default)?

In the meantime I will try to prepare a beta release as soon as possible.

**Comment by tzh1043** [comment]
The _limits_ check, being lower in the code path, would always supersede what this flicker fix wanted to set, but the latter would never be informed that the requested speed was not actually set, but that mostly resulted in wrong debug output.

Now this is checked first, and additionally (the initial reason for moving the fanspeed curve to a separate module) the corresponding temperature of the upper fanspeed fix range (wherein fan speed changed might lag behind) is checked, currently hardcoded at 75°C.

**Comment by foucault** [comment]
Things make more sense now, so I'm merging this and will update the README. Feel free to open a new PR if you want to make amendments.

**Pull request merged**
